.\" -*- nroff -*-
.\" ----------------------------------------------------------------------
.\" install-sgmlcatalog.8 : manual page for install-sgmlcatalog(8)
.\" ----------------------------------------------------------------------
.\" Copyright (c) 1997 Christian Schwarz
.\" Copyright (c) 2001-2004 Ardo van Rangelrooij
.\"
.\" This is free software; see the GNU General Public Licence version 2
.\" or later for copying conditions.  There is NO warranty.
.\" ----------------------------------------------------------------------
.\"
.\" ----------------------------------------------------------------------
.TH INSTALL-SGMLCATALOG 8 "August 2004" "Debian Project" "Debian"
.\"
.\" ----------------------------------------------------------------------
.SH NAME
install-sgmlcatalog \- maintain transitional SGML catalog
.\"
.\" ----------------------------------------------------------------------
.SH SYNOPSIS
.B install-sgmlcatalog
.B \-\-remove
.I package
.\"
.\" ----------------------------------------------------------------------
.SH DESCRIPTION
.PP
.B install-sgmlcatalog
removes entries from the transitional SGML catalog file
.BR /etc/sgml/transitional.cat .
.\"
.\" ----------------------------------------------------------------------
.SH OPTIONS
.TP
.BI \-\-remove \ package
Indicates to remove the entry for the package
.IR package .
.\"
.\" ----------------------------------------------------------------------
.SH AUTHOR
Ardo van Rangelrooij <ardo@debian.org>
.br
Christian Schwarz (original version)
.\"
.\" ----------------------------------------------------------------------
.SH COPYRIGHT
Copyright \(co 1997 Christian Schwarz
.br
Copyright \(co 2001-2004 Ardo van Rangelrooij

This is free software; see the GNU General Public Licence version 2 or
later for copying conditions.  There is
.I no
warranty.
.\"
.\" ----------------------------------------------------------------------
