.\" -*- nroff -*-
.\" ----------------------------------------------------------------------
.\" Copyright (c) 2001-2004 Ardo van Rangelrooij
.\"
.\" This is free software; see the GNU General Public Licence version 2
.\" or later for copying conditions.  There is NO warranty.
.\" ----------------------------------------------------------------------
.\"
.\" ----------------------------------------------------------------------
.TH UPDATE-CATALOG 8 "June 2004" "Debian Project" "Debian"
.\"
.\" ----------------------------------------------------------------------
.SH NAME
update-catalog \- create or update entry in SGML catalog file
.\"
.\" ----------------------------------------------------------------------
.SH SYNOPSIS
.B update-catalog
.RI [ options ]
.B --add
.I centralized_catalog ordinary_catalog
.PP
.B update-catalog
.RI [ options ]
.B --remove
.I centralized_catalog ordinary_catalog
.PP
.B update-catalog
.RI [ options ]
.B --update-super
.\"
.\" ----------------------------------------------------------------------
.SH DESCRIPTION
.PP
.B update-catalog
inserts, updates or removes entries in the 
SGML centralized catalogs located in
.IR /etc/sgml .
To change the SGML super catalog located in
.IR /etc/sgml/catalog
modify the directory contents of
.IR /etc/sgml
to contain new files or symbolic links having a
.B .cat
extension or remove (or move) existing centralized catalogs and regenerate the super catalog using the
.B --update-super
option.
See section
.B SUPER CATALOG
for details on the generation process.
.\"
.\" ----------------------------------------------------------------------
.SH OPTIONS
.TP
.B --add
Adds an entry for the
.I ordinary_catalog
in the
.IR centralized_catalog .
.TP
.B --remove
Removes the entry for the
.I ordinary_catalog
from the
.IR centralized_catalog .
.TP
.B --update-super
Regenerates the SGML super catalog from the contents of the
.IR /etc/sgml
directory.
See section
.B SUPER CATALOG
for details on the super catalog generation.
.TP
.B --quiet
Prevents the usual diagnostic output.
.TP
.B --test
Prevents the update of the catalog and writes the resulting SGML
catalog to standard output.
.TP
.B --version
Displays the version information and exits.
.TP
.B --help
Display the usage information and exits.
.\"
.\" ----------------------------------------------------------------------
.SH SUPER CATALOG
The super-catalog located in
.IR /etc/sgml/catalog
cannot be directly modified.
It is generated by the
.IR update-catalog
.IR --update-super
command.
The generation considers files in the
.IR /etc/sgml
directory that have a
.B .cat
extension.
For instance files ending in .old or .disabled are not considered.
Before adding a catalog to the super catalog it is parsed and verified in order to not corrupt the super catalog.
All referenced catalogs are verified to actually exist.
If the check fails, a message is printed and the complete catalog is ignored.
This check ensures that a catalog from a package, which is removed but not purged, is removed from the super catalog.
.\"
.\" ----------------------------------------------------------------------
.SH AUTHOR
Ardo van Rangelrooij <ardo@debian.org>
.\"
.\" ----------------------------------------------------------------------
.SH COPYRIGHT
Copyright \(co 2001-2004 Ardo van Rangelrooij
Copyright \(co 2012 Helmut Grohne

This is free software; see the GNU General Public Licence version 2 or
later for copying conditions.  There is
.I no
warranty.
.\"
.\" ----------------------------------------------------------------------
